module.exports = {
    "port": process.env.PORT || 3000,
    "environment": "dev",
    "mongoDbUri": process.env.MONGODB_URI || "mongodb://localhost/github-consumer",
    "nowToken":"dBc5Jvile7Whof3YHKN5pJjn",
    "projectApiUrl":"https://zeit.co/api/projects",
    "projectApiV1Url":"https://zeit.co/api/v1/projects",
    "projectApiV2Url":"https://zeit.co/api/v2/projects",
    "githubDeployUrl":"https://now-git-deployer.zeit.sh",
    "teamId":"team_y2WH8R3yCPynhowCRcwbpA9S",
    "githubCreateRepoUrl":"https://zeit.co/api/v1/integrations/github-create-repo",
    "githubPushRepoUrl":"https://zeit.co/api/v1/integrations/github-push-repo",
    "installationId":589845,
    "org":"han-tech",
    "gittype":"github",
    "githubToken":"d623b3fcbd818985462b532c9c44e49af59ce868",
    "prismicAuthUrl":"https://prismic.io/authentication",
    "prismicUsername":"dinhquangson@gmail.com",
    "prismicPassword":"Th@Nhb1nh"
};
