module.exports = {
    "port": process.env.PORT || 3000,
    "environment": "dev",
    "mongoDbUri": process.env.MONGODB_URI || "mongodb://localhost/github-consumer",
    "nowToken":"dBc5Jvile7Whof3YHKN5pJjn",
    "projectApiUrl":"https://zeit.co/api/projects",
    "projectApiV1Url":"https://zeit.co/api/v1/projects",
    "projectApiV2Url":"https://zeit.co/api/v2/projects",
    "githubDeployUrl":"https://now-git-deployer.zeit.sh",
    "teamId":"team_y2WH8R3yCPynhowCRcwbpA9S",
    "githubCreateRepoUrl":"https://zeit.co/api/v1/integrations/github-create-repo",
    "githubPushRepoUrl":"https://zeit.co/api/v1/integrations/github-push-repo",
    "githubToken":"e2d4f33ee3ae00392ae588a6b6d61311704f5c08",
    "installationId":589845,
    "org":"han-tech",
    "gittype":"github",
    "githubUsername":"hantech2017@gmail.com",
    "githubPassword":"Cuul0ng1",
    "butterCMSApiUrl":"https://api.buttercms.com/v2/",
    "butterCMSLoginWebhookUrl":"https://buttercms.com/login/?next=/webhooks/",
    "butterCMSWebhookUrl":"https://buttercms.com/webhooks/",
    "kontentApiUrl":"https://manage.kontent.ai/v2/projects/",
    "cosmicAuthUrl":"https://api.cosmicjs.com/v1/authenticate",
    "forestryAddSiteUrl":"https://app.forestry.io/dashboard/#/add-site",
    "forestryLoginUrl":"https://app.forestry.io/login",
    "forestryDashboardUrl":"https://app.forestry.io/dashboard/"
};
